language: R
sudo: false
cache:
  - packages: true

warnings_are_errors: true
r_check_args: "--as-cran"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libglpk-dev

matrix:
  include:
  - r: release
    r_github_packages:
    - r-lib/covr
    - r-lib/pkgdown
    after_success:
    - R CMD INSTALL $PKG_TARBALL
    - Rscript -e 'covr::coveralls()'
    - Rscript -e 'devtools::install(); devtools::test()'
    deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github()'
      skip_cleanup: true
  - r: devel
    after_success:
    - R CMD INSTALL $PKG_TARBALL
    - Rscript -e 'covr::coveralls()'
    - Rscript -e 'devtools::install(); devtools::test()'

notifications:
  email:
    on_success: always
    on_failure: always
